//
//
// graphtlp.h
//
// Charger et enregistrer l'object GraphImage sur un fichier TLP
//
// LE Viet Man
// 18/05/10
//
//

#ifndef GRAPHTLP_H
#define GRAPHTLP_H

#include <QDate>
#include "GraphImage/graphimage.h"

const QString TLP_HEADER = "(tlp 2.0";
const QString TLP_ENCLOSING = ")";

const QString TLP_DATE_BEGIN = "(date \"";
const QString TLP_DATE_END = "\")";

const QString TLP_AUTHOR = "(author \"manleviet\")";
const QString TLP_COMMENTS = "(comments \"This file was generated by convertVGI\")";

const QString TLP_SCENE = "(string \"scene\" \"<?xml version=\\\"1.0\\\"?>\n\
<scene>\n\
    <data>\n\
        <viewport>(0,0,605,634)</viewport>\n\
        <background>(202,202,202,255)</background>\n\
    </data>\n\
    <children>\n\
        <GlLayer name=\\\"Background\\\">\n\
            <data>\n\
                <camera>\n\
                    <data>\n\
                        <center>(179.679,-497.671,0)</center>\n\
                        <eyes>(179.679,-497.671,748.819)</eyes>\n\
                        <up>(0,1,0)</up>\n\
                        <zoomFactor>0.5</zoomFactor>\n\
                        <sceneRadius>748.819</sceneRadius>\n\
                        <d3>0</d3>\n\
                    </data>\n\
                </camera>\n\
                <visible>0</visible>\n\
            </data>\n\
            <children type=\\\"GlComposite\\\">\n\
                <data/>\n\
                <children>\n\
                    <GlEntity name=\\\"background\\\" type=\\\"GlRectTextured\\\">\n\
                        <data>\n\
                            <visible>1</visible>\n\
                            <stencil>65535</stencil>\n\
                            <top>0</top>\n\
                            <bottom>1</bottom>\n\
                            <left>0</left>\n\
                            <right>1</right>\n\
                            <inPercent>1</inPercent>\n\
                            <textureName>TulipBitmapDir/tex_back.png</textureName>\n\
                        </data>\n\
                    </GlEntity>\n\
                </children>\n\
            </children>\n\
        </GlLayer>\n\
        <GlLayer name=\\\"Main\\\">\n\
            <data>\n\
                <camera>\n\
                    <data>\n\
                        <center>(179.679,-497.671,0)</center>\n\
                        <eyes>(179.679,-497.671,748.819)</eyes>\n\
                        <up>(0,1,0)</up>\n\
                        <zoomFactor>0.5</zoomFactor>\n\
                        <sceneRadius>748.819</sceneRadius>\n\
                        <d3>1</d3>\n\
                    </data>\n\
                </camera>\n\
                <visible>1</visible>\n\
            </data>\n\
            <children type=\\\"GlComposite\\\">\n\
                <data/>\n\
                <children>\n\
                    <GlEntity name=\\\"Hulls\\\" type=\\\"GlComposite\\\">\n\
                        <data>\n\
                            <visible>0</visible>\n\
                            <stencil>65535</stencil>\n\
                        </data>\n\
                        <children/>\n\
                    </GlEntity>\n\
                    <GlEntity name=\\\"graph\\\" type=\\\"GlGraphComposite\\\">\n\
                        <data>\n\
                            <visible>1</visible>\n\
                            <stencil>65535</stencil>\n\
                        </data>\n\
                    </GlEntity>\n\
                </children>\n\
            </children>\n\
        </GlLayer>\n\
        <GlLayer name=\\\"Foreground\\\">\n\
            <data>\n\
                <camera>\n\
                    <data>\n\
                        <center>(179.679,-497.671,0)</center>\n\
                        <eyes>(179.679,-497.671,748.819)</eyes>\n\
                        <up>(0,1,0)</up>\n\
                        <zoomFactor>0.5</zoomFactor>\n\
                        <sceneRadius>748.819</sceneRadius>\n\
                        <d3>0</d3>\n\
                    </data>\n\
                </camera>\n\
                <visible>1</visible>\n\
            </data>\n\
            <children type=\\\"GlComposite\\\">\n\
                <data/>\n\
                <children>\n\
                    <GlEntity name=\\\"labrilogo\\\" type=\\\"GlRectTextured\\\">\n\
                        <data>\n\
                            <visible>0</visible>\n\
                            <stencil>65535</stencil>\n\
                            <top>5</top>\n\
                            <bottom>55</bottom>\n\
                            <left>5</left>\n\
                            <right>55</right>\n\
                            <inPercent>0</inPercent>\n\
                            <textureName>TulipBitmapDir/logolabri.jpg</textureName>\n\
                        </data>\n\
                    </GlEntity>\n\
                </children>\n\
            </children>\n\
        </GlLayer>\n\
    </children>\n\
</scene>\n\
\")";

class GraphTLP
{
public:
    GraphTLP(GraphImage *graph);

    bool saveGraph(bool simple, const QString &filename);

private:
    GraphImage *graph;

    QString getContentVGI1Complet();
    QString getContentVGI1CompletTagNodes();
    QString getContentVGI1CompletTagEdges();
    QString getContentVGI1CompletTagPropertyCluster();
    QString getContentVGI1CompletTagColor();
    QString getContentVGI1CompletTagLabel();
    QString getContentVGI1CompletTagTexture();

    QString getContentVGI1Simple();
    QString getContentVGI1SimpleTagNodes();
    QString getContentVGI1SimpleTagEdges();
    QString getContentVGI1SimpleTagPropertyCluster();
    QString getContentVGI1SimpleTagColor();
    QString getContentVGI1SimpleTagLabel();
    QString getContentVGI1SimpleTagTexture();

    QString getContentVGI2Simple();
    QString getContentVGI2SimpleTagNodes();
    QString getContentVGI2SimpleTagEdges();
    QString getContentVGI2SimpleTagPropertyCluster();
    QString getContentVGI2SimpleTagColor();
    QString getContentVGI2SimpleTagLabel();
    QString getContentVGI2SimpleTagTexture();

    QString getContentTagAttributes();
};
#endif // GRAPHTLP_H
